package com.angryelectron.femulator.mapviewer;

import com.angryelectron.femulator.f1api.F1Utils;
import javax.swing.DefaultComboBoxModel;

public class MidiPanel extends javax.swing.JPanel {

    /**
     * Creates new form MidiPanel
     */
    public MidiPanel() {
        initComponents();
    }       
    
    public String getSelectedMidiDevice() {
        return jComboBox1.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MidiPanel.class, "MidiPanel.jLabel1.text")); // NOI18N
        add(jLabel1);

        jComboBox1.setModel(new DefaultComboBoxModel(F1Utils.listMidiDevices()));
        add(jComboBox1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
