package com.angryelectron.femulator.mapviewer;

public class NamePanel extends javax.swing.JPanel {

    /**
     * Creates new form NamePanel
     */
    public NamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NamePanel.class, "NamePanel.jLabel1.text")); // NOI18N
        add(jLabel1);

        nameTextField.setText(org.openide.util.NbBundle.getMessage(NamePanel.class, "NamePanel.nameTextField.text")); // NOI18N
        nameTextField.setToolTipText(org.openide.util.NbBundle.getMessage(NamePanel.class, "NamePanel.nameTextField.toolTipText")); // NOI18N
        nameTextField.setPreferredSize(new java.awt.Dimension(200, 28));
        add(nameTextField);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
    
    public String getValue() {
        return nameTextField.getText();
    }
    
    public void setValue(String name) {
        nameTextField.setText(name);        
    }
}
